--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/FresherGAMING/ManaStats
build-by-default: true
branches:
- main
projects:
  Mana:
    path: ""
    libs: 
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: poggit/libasynql/libasynql
        version: ^4.2.0

...
