name: ManaStats
main: FresherGAMING\Mana\Mana
api: 5.0.0
version: 1.0.0
author: FresherGAMING
permissions:
  mana.cmd:
    default: true
  mana.cmd.others:
    default: op
  managemana.cmd:
    default: op
  managemanaregen.cmd:
    default: op
  managemaxmana.cmd:
    default: op