name: ManaStats
main: FresherGAMING\Mana\ManaStats
api: 5.0.0
version: 1.0.0
author: FresherGAMING
permissions:
  manastats.mana.cmd:
    default: true
  manastats.mana.cmd.others:
    default: op
  manastats.managemana.cmd:
    default: op
  manastats.managemanaregen.cmd:
    default: op
  manastats.managemaxmana.cmd:
    default: op
  manastats.mana.bypass:
    default: false